/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	"context"
	"time"

	v2 "github.com/mattmoor/warm-image/pkg/apis/warmimage/v2"
	scheme "github.com/mattmoor/warm-image/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WarmImagesGetter has a method to return a WarmImageInterface.
// A group's client should implement this interface.
type WarmImagesGetter interface {
	WarmImages(namespace string) WarmImageInterface
}

// WarmImageInterface has methods to work with WarmImage resources.
type WarmImageInterface interface {
	Create(ctx context.Context, warmImage *v2.WarmImage, opts v1.CreateOptions) (*v2.WarmImage, error)
	Update(ctx context.Context, warmImage *v2.WarmImage, opts v1.UpdateOptions) (*v2.WarmImage, error)
	UpdateStatus(ctx context.Context, warmImage *v2.WarmImage, opts v1.UpdateOptions) (*v2.WarmImage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.WarmImage, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.WarmImageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.WarmImage, err error)
	WarmImageExpansion
}

// warmImages implements WarmImageInterface
type warmImages struct {
	client rest.Interface
	ns     string
}

// newWarmImages returns a WarmImages
func newWarmImages(c *MattmoorV2Client, namespace string) *warmImages {
	return &warmImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the warmImage, and returns the corresponding warmImage object, and an error if there is any.
func (c *warmImages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.WarmImage, err error) {
	result = &v2.WarmImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("warmimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WarmImages that match those selectors.
func (c *warmImages) List(ctx context.Context, opts v1.ListOptions) (result *v2.WarmImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.WarmImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("warmimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested warmImages.
func (c *warmImages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("warmimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a warmImage and creates it.  Returns the server's representation of the warmImage, and an error, if there is any.
func (c *warmImages) Create(ctx context.Context, warmImage *v2.WarmImage, opts v1.CreateOptions) (result *v2.WarmImage, err error) {
	result = &v2.WarmImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("warmimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(warmImage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a warmImage and updates it. Returns the server's representation of the warmImage, and an error, if there is any.
func (c *warmImages) Update(ctx context.Context, warmImage *v2.WarmImage, opts v1.UpdateOptions) (result *v2.WarmImage, err error) {
	result = &v2.WarmImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("warmimages").
		Name(warmImage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(warmImage).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *warmImages) UpdateStatus(ctx context.Context, warmImage *v2.WarmImage, opts v1.UpdateOptions) (result *v2.WarmImage, err error) {
	result = &v2.WarmImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("warmimages").
		Name(warmImage.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(warmImage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the warmImage and deletes it. Returns an error if one occurs.
func (c *warmImages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("warmimages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *warmImages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("warmimages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched warmImage.
func (c *warmImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.WarmImage, err error) {
	result = &v2.WarmImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("warmimages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
